on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        description: Select the environment
        default: "test"
      boolean:
        type: boolean
        description: with or without tests
        default: true
      SomeOption:
        type: choice
        description: Select Version
        options:
        - foo
        - bar
        - baz
  push:
    branches: [ main ]
  


jobs:
  testjob:
    name: TestJob 
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Test our shell script
        run: |
          echo "${{ github.event.inputs.SomeOption }}"
          pip install pandas
          pip install setuptools