on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      # tags:
      #   description: 'Test scenario tags'
      #   required: false
      #   type: boolean
      # environment:
      #   description: 'Environment to run tests against'
      #   type: environment
      #   required: true
  push:
    branches: [ main ]

jobs:
  UnitTests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: run unit tests
        run: |
          pip install pytest
          cd EreklesPackage
          pytest test.py
          echo Here is the log level on Tests Step ${{ inputs.logLevel }}

  BuildPackage:
    name: Build the Package
    runs-on: ubuntu-latest
    needs: UnitTests

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: build package
        run: |
          pip install pytest setuptools wheel
          pwd
          ls -laF
          which python
          python ./setup.py bdist_wheel
          echo Here is the log level on Build Step ${{ inputs.logLevel }}


      - uses: actions/upload-artifact@v3
        with:
          name: EreklesPackage-1.0-py2.py3-none-any.whl
          path: EreklesPackage/dist/*