on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        description: Select the environment
        default: "test"
      boolean:
        type: boolean
        description: with or without tests
        default: true
      SomeOption:
        type: choice
        description: Select Version
        options:
        - foo
        - bar
        - baz
  push:
    branches: [ main ]

jobs:
  UnitTests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install pytest
        run: pip install pytest

      - name: run unit tests
        run: |
          cd EreklesPackage
          pytest test.py

  BuildPackage:
    name: Build the Package
    runs-on: ubuntu-latest
    needs: UnitTests

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install pandas
        run: pip install pandas

      - name: Install setuptools
        run: pip install setuptools
      - name: Print current directory
        run: pwd

      - name: Build package
        run: |
          cd ../../
          pwd
          ls  
          # cd EreklesPackage
          python setup.py bdist_wheel

      - uses: actions/upload-artifact@v3
        with:
          name: EreklesPackage-1.0-py2.py3-none-any.whl
          path: EreklesPackage/dist/*
