on:
  push:
    branches: [ main ]

jobs:
  buildandpush:
    name: BuildandPush
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: run unit tests
        run: |
          pip install pytest
          pip install setuptools
          cd EreklesPackage
          pytest test.py